### ISSUE TITLE
[Feature]: Extension icon could be better

### ISSUE THREAD

**Issue by 956MB** [tektronix/tsp-toolkit#21]
### Pre-check

- [X] I have searched the existing issues and discussions to make sure my problem has not already been addressed.
- [X] I have looked at the "Known Issues" Section of the marketplace page of all TSP Toolkit extensions.

### Feature Idea

The sidebar icon for the extension should probably be a bit more in line with the style of VSCode's default icons. There is also an opportunity to use the Tektronix logo, if possible. I don't know the "rules" about using the logo in something like this extension, so this is just a suggestion and it'd be up to you guys.

Here's a _preliminary_ svg I made to get the point across though:

Before             |  After
:-------------------------:|:-------------------------:
<img width="150" alt="TektronixVSCodeLogo-TSP" src="https://github.com/tektronix/tsp-toolkit/assets/39519792/5e348e13-5af3-4812-8c78-83c2580dbfed">  |  <img width="150" alt="TektronixVSCodeLogo-Logo" src="https://github.com/tektronix/tsp-toolkit/assets/39519792/b1e859d2-c05c-4b0e-83e1-85edf742ab47">

SVG:

<img src="https://github.com/tektronix/tsp-toolkit/assets/39519792/d424436b-2b1e-4f99-b312-8207d76ceba5" width="100" />

**Comment by esarver** [comment]
Thanks for this idea. Unfortunately, branding is not something that we can discuss changing.

**Comment by 956MB** [comment]
:( btw `bug` and `triage` are the default labels for the Feature Request template in [.github/ISSUE_TEMPLATE/01-feature.yml](.github/ISSUE_TEMPLATE/01-feature.yml), "enhancement" chould probably be default.
